# Generated by Django 3.1.5 on 2021-02-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_service_category_icon'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('booked_date', models.DateField()),
                ('booked_time', models.TimeField()),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_category')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='postcode',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
        migrations.AddField(
            model_name='bookinglineitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.booking'),
        ),
        migrations.AddField(
            model_name='bookinglineitem',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.tasker'),
        ),
    ]
