# Generated by Django 3.1.5 on 2021-03-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210222_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglineitem',
            name='Service',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
