# Generated by Django 3.1.5 on 2021-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210318_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglineitem',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
