# Generated by Django 3.1.5 on 2021-02-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_category', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'service',
            },
        ),
        migrations.CreateModel(
            name='sub_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Service_name', models.CharField(max_length=254)),
                ('Service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
            options={
                'verbose_name_plural': 'sub_Service',
            },
        ),
        migrations.CreateModel(
            name='tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('about', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2054)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Tasker_service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
                ('tasker_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.sub_service')),
            ],
            options={
                'verbose_name_plural': 'tasker',
            },
        ),
    ]
