# Generated by Django 3.1.5 on 2021-02-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_category', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Service_name', models.CharField(max_length=254)),
                ('Service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(max_length=1054, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Tasker_service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
                ('tasker_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.sub_service')),
            ],
        ),
    ]
