# Generated by Django 3.1.5 on 2021-02-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='Service_category',
        ),
        migrations.AlterModelOptions(
            name='service_category',
            options={'verbose_name_plural': 'services'},
        ),
        migrations.RenameField(
            model_name='service_category',
            old_name='Service_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sub_service',
            old_name='Service_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sub_service',
            old_name='Sub_Service_name',
            new_name='sub_service_name',
        ),
        migrations.RenameField(
            model_name='tasker',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasker',
            old_name='Price',
            new_name='price',
        ),
    ]
