# Generated by Django 3.1.5 on 2021-02-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210209_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_category',
            options={'verbose_name_plural': 'service'},
        ),
    ]
