# Generated by Django 3.1.5 on 2021-02-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210209_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasker',
            old_name='Tasker_service_category',
            new_name='service_category',
        ),
    ]
