# Generated by Django 3.1.5 on 2021-02-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210211_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='charge_type',
            field=models.CharField(default='Hourly', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_category',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
