# Generated by Django 3.1.5 on 2021-02-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210220_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Charge_type',
            },
        ),
        migrations.RemoveField(
            model_name='service_category',
            name='charge_type',
        ),
        migrations.AddField(
            model_name='tasker',
            name='charge_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.charge_type'),
        ),
    ]
