# Generated by Django 3.1.5 on 2021-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210220_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='image_url',
            field=models.URLField(blank=True, max_length=10000),
        ),
    ]
