# Generated by Django 3.1.5 on 2021-02-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_tasker_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
            preserve_default=False,
        ),
    ]
