# Generated by Django 3.1.5 on 2021-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20210220_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='icon',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
