# Generated by Django 3.1.5 on 2021-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_service_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
